package com.careflow.scheduling.dto;

import java.time.LocalDate;
import java.time.LocalTime;

/**
 * Representation of an available appointment slot generated by the scheduling engine (§18, §103 Phase 4).
 */
public record AvailableSlotResponse(
        String doctorId,
        LocalDate date,
        LocalTime startTime,
        LocalTime endTime,
        String status
) {
}
